apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l0g3w2fgu-go 
  janus-idp.io/tekton: l0g3w2fgu-go
  backstage.io/kubernetes-id: l0g3w2fgu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l0g3w2fgu-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  