apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l0g3w2fgu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l0g3w2fgu-go 
  name: l0g3w2fgu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l0g3w2fgu-go 
